/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package ec.edu.ups.sistemabibliotecaview.menuview.principalview;

/**
 *
 * @author katherine
 */
public class MenuView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuView.class.getName());

    /**
     * Creates new form MenuUsuarioView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel83 = new javax.swing.JPanel();
        jPanel84 = new javax.swing.JPanel();
        btnInicio16 = new javax.swing.JButton();
        btnAutores16 = new javax.swing.JButton();
        btnBibliotecarios16 = new javax.swing.JButton();
        btnPrestamo16 = new javax.swing.JButton();
        btnDevoluciones16 = new javax.swing.JButton();
        btnLibros16 = new javax.swing.JButton();
        jPanel85 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabelMBienvenida = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelInformacionP1 = new javax.swing.JLabel();
        jLabelInformacionP2 = new javax.swing.JLabel();
        jLabelInformacionP3 = new javax.swing.JLabel();
        jLabelInformacionP4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenuBibliotecario = new javax.swing.JMenu();
        jMenuBibliotecarioAgregar = new javax.swing.JMenuItem();
        jMenuBibliotecarioBuscar = new javax.swing.JMenuItem();
        jMenuBibliotecarioEliminar = new javax.swing.JMenuItem();
        jMenuBibliotecarioActualizar = new javax.swing.JMenuItem();
        jMenuAutor = new javax.swing.JMenu();
        jMenuAutorAgregar = new javax.swing.JMenuItem();
        jMenuAutorBuscar = new javax.swing.JMenuItem();
        jMenuAutorEliminar = new javax.swing.JMenuItem();
        jMenuAutorActualizar = new javax.swing.JMenuItem();
        fileMenuUsuario = new javax.swing.JMenu();
        jMenuAgregar = new javax.swing.JMenuItem();
        jMenuBuscar = new javax.swing.JMenuItem();
        jMenuEliminar = new javax.swing.JMenuItem();
        jMenuActualizar = new javax.swing.JMenuItem();
        jMenuPrestamo = new javax.swing.JMenu();
        jMenuPrestamoAgregar = new javax.swing.JMenuItem();
        jMenuPrestamoBuscar = new javax.swing.JMenuItem();
        jMenuPrestamoListar = new javax.swing.JMenuItem();
        jMenuDevolucion = new javax.swing.JMenu();
        jMenuDevolucionAgregar = new javax.swing.JMenuItem();
        jMenuIdioma = new javax.swing.JMenu();
        jMenuIdiomaSpaniol = new javax.swing.JMenuItem();
        jMenuIdiomaIngles = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jPanel83.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel84Layout = new javax.swing.GroupLayout(jPanel84);
        jPanel84.setLayout(jPanel84Layout);
        jPanel84Layout.setHorizontalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jPanel84Layout.setVerticalGroup(
            jPanel84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        btnInicio16.setBackground(new java.awt.Color(153, 153, 153));
        btnInicio16.setText("Inicio");

        btnAutores16.setBackground(new java.awt.Color(153, 153, 153));
        btnAutores16.setText("Autores");

        btnBibliotecarios16.setBackground(new java.awt.Color(153, 153, 153));
        btnBibliotecarios16.setText("Bibliotecarios");
        btnBibliotecarios16.addActionListener(this::btnBibliotecarios16ActionPerformed);

        btnPrestamo16.setBackground(new java.awt.Color(153, 153, 153));
        btnPrestamo16.setText("Prestamos");
        btnPrestamo16.addActionListener(this::btnPrestamo16ActionPerformed);

        btnDevoluciones16.setBackground(new java.awt.Color(153, 153, 153));
        btnDevoluciones16.setText("Devoluciones");
        btnDevoluciones16.addActionListener(this::btnDevoluciones16ActionPerformed);

        btnLibros16.setBackground(new java.awt.Color(153, 153, 153));
        btnLibros16.setText("Libros");
        btnLibros16.addActionListener(this::btnLibros16ActionPerformed);

        javax.swing.GroupLayout jPanel85Layout = new javax.swing.GroupLayout(jPanel85);
        jPanel85.setLayout(jPanel85Layout);
        jPanel85Layout.setHorizontalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        jPanel85Layout.setVerticalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel83Layout = new javax.swing.GroupLayout(jPanel83);
        jPanel83.setLayout(jPanel83Layout);
        jPanel83Layout.setHorizontalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addGroup(jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel83Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel83Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBibliotecarios16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAutores16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInicio16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel83Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDevoluciones16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrestamo16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel83Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLibros16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel83Layout.setVerticalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnInicio16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutores16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBibliotecarios16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestamo16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevoluciones16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLibros16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelMBienvenida.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabelMBienvenida.setText("!BIENVENIDO AL SISTEMA¡");

        jPanel61.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMBienvenida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelMBienvenida)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelInformacionP1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelInformacionP1.setText("Organiza, administra ");

        jLabelInformacionP2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelInformacionP2.setText("y transforma el conocimiento.");

        jLabelInformacionP3.setText("Cada libro que registras, es una puerta ");

        jLabelInformacionP4.setText("que habres a un nuevo mundo.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInformacionP3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformacionP1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelInformacionP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelInformacionP2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelInformacionP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInformacionP2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInformacionP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInformacionP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        menuBar.setBackground(new java.awt.Color(0, 0, 0));

        jMenuBibliotecario.setText("Bibliotecario");

        jMenuBibliotecarioAgregar.setText("Agregar");
        jMenuBibliotecario.add(jMenuBibliotecarioAgregar);

        jMenuBibliotecarioBuscar.setText("Buscar");
        jMenuBibliotecario.add(jMenuBibliotecarioBuscar);

        jMenuBibliotecarioEliminar.setText("Eliminar");
        jMenuBibliotecario.add(jMenuBibliotecarioEliminar);

        jMenuBibliotecarioActualizar.setText("Actualizar");
        jMenuBibliotecario.add(jMenuBibliotecarioActualizar);

        menuBar.add(jMenuBibliotecario);

        jMenuAutor.setText("Autor");

        jMenuAutorAgregar.setText("Agregar");
        jMenuAutorAgregar.addActionListener(this::jMenuAutorAgregarActionPerformed);
        jMenuAutor.add(jMenuAutorAgregar);

        jMenuAutorBuscar.setText("Buscar");
        jMenuAutor.add(jMenuAutorBuscar);

        jMenuAutorEliminar.setText("Eliminar");
        jMenuAutor.add(jMenuAutorEliminar);

        jMenuAutorActualizar.setText("Actualizar");
        jMenuAutor.add(jMenuAutorActualizar);

        menuBar.add(jMenuAutor);

        fileMenuUsuario.setMnemonic('f');
        fileMenuUsuario.setText("Usuario");

        jMenuAgregar.setMnemonic('o');
        jMenuAgregar.setText("Agregar");
        fileMenuUsuario.add(jMenuAgregar);

        jMenuBuscar.setMnemonic('s');
        jMenuBuscar.setText("Buscar");
        fileMenuUsuario.add(jMenuBuscar);

        jMenuEliminar.setMnemonic('a');
        jMenuEliminar.setText("Eliminar");
        fileMenuUsuario.add(jMenuEliminar);

        jMenuActualizar.setMnemonic('x');
        jMenuActualizar.setText("Actualizar");
        jMenuActualizar.addActionListener(this::jMenuActualizarActionPerformed);
        fileMenuUsuario.add(jMenuActualizar);

        menuBar.add(fileMenuUsuario);

        jMenuPrestamo.setText("Prestamo");

        jMenuPrestamoAgregar.setText("Agregar");
        jMenuPrestamo.add(jMenuPrestamoAgregar);

        jMenuPrestamoBuscar.setText("Buscar");
        jMenuPrestamo.add(jMenuPrestamoBuscar);

        jMenuPrestamoListar.setText("Listar");
        jMenuPrestamo.add(jMenuPrestamoListar);

        menuBar.add(jMenuPrestamo);

        jMenuDevolucion.setText("Devolucion");

        jMenuDevolucionAgregar.setText("Agregar");
        jMenuDevolucion.add(jMenuDevolucionAgregar);

        menuBar.add(jMenuDevolucion);

        jMenuIdioma.setText("Idioma");

        jMenuIdiomaSpaniol.setText("Español");
        jMenuIdioma.add(jMenuIdiomaSpaniol);

        jMenuIdiomaIngles.setText("Ingles");
        jMenuIdiomaIngles.addActionListener(this::jMenuIdiomaInglesActionPerformed);
        jMenuIdioma.add(jMenuIdiomaIngles);

        menuBar.add(jMenuIdioma);

        jMenu1.setText("Volver");
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActualizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuActualizarActionPerformed

    private void btnBibliotecarios16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecarios16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBibliotecarios16ActionPerformed

    private void btnPrestamo16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamo16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestamo16ActionPerformed

    private void btnDevoluciones16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevoluciones16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevoluciones16ActionPerformed

    private void btnLibros16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibros16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibros16ActionPerformed

    private void jMenuIdiomaInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIdiomaInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIdiomaInglesActionPerformed

    private void jMenuAutorAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAutorAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAutorAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores16;
    private javax.swing.JButton btnBibliotecarios16;
    private javax.swing.JButton btnDevoluciones16;
    private javax.swing.JButton btnInicio16;
    private javax.swing.JButton btnLibros16;
    private javax.swing.JButton btnPrestamo16;
    private javax.swing.JMenu fileMenuUsuario;
    private javax.swing.JLabel jLabelInformacionP1;
    private javax.swing.JLabel jLabelInformacionP2;
    private javax.swing.JLabel jLabelInformacionP3;
    private javax.swing.JLabel jLabelInformacionP4;
    private javax.swing.JLabel jLabelMBienvenida;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuActualizar;
    private javax.swing.JMenuItem jMenuAgregar;
    private javax.swing.JMenu jMenuAutor;
    private javax.swing.JMenuItem jMenuAutorActualizar;
    private javax.swing.JMenuItem jMenuAutorAgregar;
    private javax.swing.JMenuItem jMenuAutorBuscar;
    private javax.swing.JMenuItem jMenuAutorEliminar;
    private javax.swing.JMenu jMenuBibliotecario;
    private javax.swing.JMenuItem jMenuBibliotecarioActualizar;
    private javax.swing.JMenuItem jMenuBibliotecarioAgregar;
    private javax.swing.JMenuItem jMenuBibliotecarioBuscar;
    private javax.swing.JMenuItem jMenuBibliotecarioEliminar;
    private javax.swing.JMenuItem jMenuBuscar;
    private javax.swing.JMenu jMenuDevolucion;
    private javax.swing.JMenuItem jMenuDevolucionAgregar;
    private javax.swing.JMenuItem jMenuEliminar;
    private javax.swing.JMenu jMenuIdioma;
    private javax.swing.JMenuItem jMenuIdiomaIngles;
    private javax.swing.JMenuItem jMenuIdiomaSpaniol;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuPrestamo;
    private javax.swing.JMenuItem jMenuPrestamoAgregar;
    private javax.swing.JMenuItem jMenuPrestamoBuscar;
    private javax.swing.JMenuItem jMenuPrestamoListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
