/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabibliotecaview.menuview.prestamoview;

/**
 *
 * @author katherine
 */
public class BuscarPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPrestamoView
     */
    public BuscarPrestamoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarUsuarioPrestamo = new javax.swing.JButton();
        btnBuscarLibro = new javax.swing.JButton();
        jLabelCodigoBuscarPrestamo = new javax.swing.JLabel();
        txtBuscarPrestamoCodigo = new javax.swing.JTextField();
        jLabelCedulaBuscarPrestamo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnCancelarBuscarPrestamo = new javax.swing.JButton();
        txtBuscarPrestamoUsuario = new javax.swing.JTextField();
        btnBBuscarPrestamo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelIsbnBuscarPrestamo = new javax.swing.JLabel();
        txtBuscarPrestamoNombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtBuscarPrestamoLibro = new javax.swing.JTextField();
        jLabelNombreBuscarPrestamo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTituloBuscarPrestamo = new javax.swing.JLabel();
        txtBuscarPrestamoTitulo = new javax.swing.JTextField();
        jLabelCodigoBibliotecarioBuscarPrestamo = new javax.swing.JLabel();
        txtBuscarPrestamoBibliotecario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelBuscarPrestamo = new javax.swing.JLabel();
        jLabelFechaPrestamoBuscarPrestamo = new javax.swing.JLabel();
        txtBuscarPrestamoFecha = new javax.swing.JTextField();

        btnBuscarUsuarioPrestamo.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarUsuarioPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarUsuarioPrestamo.setText("Buscar");
        btnBuscarUsuarioPrestamo.addActionListener(this::btnBuscarUsuarioPrestamoActionPerformed);

        btnBuscarLibro.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(this::btnBuscarLibroActionPerformed);

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Prestamo");

        jLabelCodigoBuscarPrestamo.setText("Codigo del Prestamo:");

        jLabelCedulaBuscarPrestamo.setText("Usuario(Cedula):");

        btnCancelarBuscarPrestamo.setText("Cancelar");
        btnCancelarBuscarPrestamo.addActionListener(this::btnCancelarBuscarPrestamoActionPerformed);

        btnBBuscarPrestamo.setBackground(new java.awt.Color(0, 102, 153));
        btnBBuscarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnBBuscarPrestamo.setText("Buscar");
        btnBBuscarPrestamo.addActionListener(this::btnBBuscarPrestamoActionPerformed);

        jLabelIsbnBuscarPrestamo.setText("Libro(ISBN):");

        jLabelNombreBuscarPrestamo.setText("Nombre:");

        jLabelTituloBuscarPrestamo.setText("Titulo:");

        jLabelCodigoBibliotecarioBuscarPrestamo.setText("Bibliotecario(Codigo):");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBuscarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBuscarPrestamo.setText("REGISTRO DE PRESTAMO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelBuscarPrestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarPrestamo)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelFechaPrestamoBuscarPrestamo.setText("Fecha prestamo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCedulaBuscarPrestamo)
                                    .addComponent(jLabelNombreBuscarPrestamo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBuscarPrestamoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtBuscarPrestamoUsuario))
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelIsbnBuscarPrestamo)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTituloBuscarPrestamo)
                                        .addGap(47, 47, 47)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBuscarPrestamoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(txtBuscarPrestamoLibro))
                                .addGap(106, 106, 106))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelCodigoBibliotecarioBuscarPrestamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarPrestamoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtBuscarPrestamoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelFechaPrestamoBuscarPrestamo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCodigoBuscarPrestamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarPrestamoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCancelarBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoBuscarPrestamo)
                    .addComponent(txtBuscarPrestamoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedulaBuscarPrestamo)
                    .addComponent(txtBuscarPrestamoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarPrestamoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreBuscarPrestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIsbnBuscarPrestamo)
                    .addComponent(txtBuscarPrestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloBuscarPrestamo)
                    .addComponent(txtBuscarPrestamoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoBibliotecarioBuscarPrestamo)
                    .addComponent(txtBuscarPrestamoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabelFechaPrestamoBuscarPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarPrestamoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnCancelarBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBuscarPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarBuscarPrestamoActionPerformed

    private void btnBBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBuscarPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBBuscarPrestamoActionPerformed

    private void btnBuscarUsuarioPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarUsuarioPrestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBBuscarPrestamo;
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarUsuarioPrestamo;
    private javax.swing.JButton btnCancelarBuscarPrestamo;
    private javax.swing.JLabel jLabelBuscarPrestamo;
    private javax.swing.JLabel jLabelCedulaBuscarPrestamo;
    private javax.swing.JLabel jLabelCodigoBibliotecarioBuscarPrestamo;
    private javax.swing.JLabel jLabelCodigoBuscarPrestamo;
    private javax.swing.JLabel jLabelFechaPrestamoBuscarPrestamo;
    private javax.swing.JLabel jLabelIsbnBuscarPrestamo;
    private javax.swing.JLabel jLabelNombreBuscarPrestamo;
    private javax.swing.JLabel jLabelTituloBuscarPrestamo;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtBuscarPrestamoBibliotecario;
    private javax.swing.JTextField txtBuscarPrestamoCodigo;
    private javax.swing.JTextField txtBuscarPrestamoFecha;
    private javax.swing.JTextField txtBuscarPrestamoLibro;
    private javax.swing.JTextField txtBuscarPrestamoNombre;
    private javax.swing.JTextField txtBuscarPrestamoTitulo;
    private javax.swing.JTextField txtBuscarPrestamoUsuario;
    // End of variables declaration//GEN-END:variables
}
