/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabibliotecaview.menuview.AutorView;

/**
 *
 * @author katherine
 */
public class ActualizarAutorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarAutorView
     */
    public ActualizarAutorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtActualizarAutorApellido = new javax.swing.JTextField();
        txtActualizarAutorBibliografia = new javax.swing.JTextField();
        jLabelApellidoAutor = new javax.swing.JLabel();
        btbGuardarActualizarAutor = new javax.swing.JButton();
        txtActualizarAutorNombre = new javax.swing.JTextField();
        btbCancelarActualizarAutor = new javax.swing.JButton();
        txtActualizarAutorFecha = new javax.swing.JTextField();
        jLabelNombreAutor = new javax.swing.JLabel();
        txtActualizarAutorCedula = new javax.swing.JTextField();
        jLabelFechaNacimientoAutor = new javax.swing.JLabel();
        jLabelCedulaAutor = new javax.swing.JLabel();
        txtActualizarAutorGenero = new javax.swing.JTextField();
        jLabelGeneroLiterarioAutor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelActualizarAutor = new javax.swing.JLabel();
        txtActualizarAutorTelefono = new javax.swing.JTextField();
        jLabelTelefonoAutor = new javax.swing.JLabel();
        txtActualizarAutorNacionalidad = new javax.swing.JTextField();
        jLabelNacionalidadAutor = new javax.swing.JLabel();
        jLabelBibliografiaAutor = new javax.swing.JLabel();
        btbBuscarActualizarAutor = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Autor");
        setToolTipText("");

        jLabelApellidoAutor.setText("Apellido:");

        btbGuardarActualizarAutor.setBackground(new java.awt.Color(0, 102, 153));
        btbGuardarActualizarAutor.setForeground(new java.awt.Color(255, 255, 255));
        btbGuardarActualizarAutor.setText("Guardar");
        btbGuardarActualizarAutor.addActionListener(this::btbGuardarActualizarAutorActionPerformed);

        btbCancelarActualizarAutor.setText("Cancelar");
        btbCancelarActualizarAutor.addActionListener(this::btbCancelarActualizarAutorActionPerformed);

        jLabelNombreAutor.setText("Nombre:");

        jLabelFechaNacimientoAutor.setText("Fecha de Nacimiento:");

        jLabelCedulaAutor.setText("Cedula:");

        jLabelGeneroLiterarioAutor.setText("Genero Literario:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelActualizarAutor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelActualizarAutor.setText("ACTUALIZAR AUTOR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabelActualizarAutor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualizarAutor)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelTelefonoAutor.setText("Telefono:");

        jLabelNacionalidadAutor.setText("Nacionalidad:");

        jLabelBibliografiaAutor.setText("Bibliografia:");

        btbBuscarActualizarAutor.setBackground(new java.awt.Color(0, 102, 153));
        btbBuscarActualizarAutor.setForeground(new java.awt.Color(255, 255, 255));
        btbBuscarActualizarAutor.setText("Buscar");
        btbBuscarActualizarAutor.addActionListener(this::btbBuscarActualizarAutorActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtActualizarAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelNombreAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtActualizarAutorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelCedulaAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtActualizarAutorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelApellidoAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtActualizarAutorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelNacionalidadAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtActualizarAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelTelefonoAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtActualizarAutorGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelGeneroLiterarioAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFechaNacimientoAutor)
                                .addComponent(jLabelBibliografiaAutor)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btbGuardarActualizarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btbCancelarActualizarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtActualizarAutorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtActualizarAutorBibliografia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btbBuscarActualizarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCedulaAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActualizarAutorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbBuscarActualizarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNombreAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelApellidoAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarAutorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNacionalidadAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarAutorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefonoAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGeneroLiterarioAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarAutorGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaNacimientoAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarAutorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBibliografiaAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarAutorBibliografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbGuardarActualizarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbCancelarActualizarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbGuardarActualizarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGuardarActualizarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbGuardarActualizarAutorActionPerformed

    private void btbCancelarActualizarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarActualizarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbCancelarActualizarAutorActionPerformed

    private void btbBuscarActualizarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarActualizarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbBuscarActualizarAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbBuscarActualizarAutor;
    private javax.swing.JButton btbCancelarActualizarAutor;
    private javax.swing.JButton btbGuardarActualizarAutor;
    private javax.swing.JLabel jLabelActualizarAutor;
    private javax.swing.JLabel jLabelApellidoAutor;
    private javax.swing.JLabel jLabelBibliografiaAutor;
    private javax.swing.JLabel jLabelCedulaAutor;
    private javax.swing.JLabel jLabelFechaNacimientoAutor;
    private javax.swing.JLabel jLabelGeneroLiterarioAutor;
    private javax.swing.JLabel jLabelNacionalidadAutor;
    private javax.swing.JLabel jLabelNombreAutor;
    private javax.swing.JLabel jLabelTelefonoAutor;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtActualizarAutorApellido;
    private javax.swing.JTextField txtActualizarAutorBibliografia;
    private javax.swing.JTextField txtActualizarAutorCedula;
    private javax.swing.JTextField txtActualizarAutorFecha;
    private javax.swing.JTextField txtActualizarAutorGenero;
    private javax.swing.JTextField txtActualizarAutorNacionalidad;
    private javax.swing.JTextField txtActualizarAutorNombre;
    private javax.swing.JTextField txtActualizarAutorTelefono;
    // End of variables declaration//GEN-END:variables
}
