/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabibliotecaview.menuview.AutorView;

/**
 *
 * @author katherine
 */
public class BuscarAutorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarAutorView
     */
    public BuscarAutorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btbGuardarUsuario2 = new javax.swing.JButton();
        txtBuscarAutorApellido = new javax.swing.JTextField();
        txtBuscarAutorBibliografia = new javax.swing.JTextField();
        jLabelApellidoBuscarAutor = new javax.swing.JLabel();
        btnBuscarAutor = new javax.swing.JButton();
        txtBuscarAutorNombre = new javax.swing.JTextField();
        btnCancelarBuscarAutor = new javax.swing.JButton();
        txtBuscarAutorFecha = new javax.swing.JTextField();
        jLabelNombreBuscarAutor = new javax.swing.JLabel();
        txtBuscarAutorCedula = new javax.swing.JTextField();
        jLabelFechaNacimientoBuscarAutor = new javax.swing.JLabel();
        jLabelCedulaBuscarAutor = new javax.swing.JLabel();
        txtBuscarAutorGenero = new javax.swing.JTextField();
        jLabelGeneroLiterarioBuscarAutor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelBuscarAutor = new javax.swing.JLabel();
        txtBuscarAutorTelefono = new javax.swing.JTextField();
        jLabelTelefonoBuscarAutor = new javax.swing.JLabel();
        txtBuscarAutorNacionalidad = new javax.swing.JTextField();
        jLabelNacionalidadBuscarAutor = new javax.swing.JLabel();
        jLabelBibliografiaBuscarAutor = new javax.swing.JLabel();

        btbGuardarUsuario2.setBackground(new java.awt.Color(0, 102, 153));
        btbGuardarUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        btbGuardarUsuario2.setText("Buscar");
        btbGuardarUsuario2.addActionListener(this::btbGuardarUsuario2ActionPerformed);

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Autor");

        jLabelApellidoBuscarAutor.setText("Apellido:");

        btnBuscarAutor.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarAutor.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAutor.setText("Buscar");
        btnBuscarAutor.addActionListener(this::btnBuscarAutorActionPerformed);

        btnCancelarBuscarAutor.setText("Cancelar");
        btnCancelarBuscarAutor.addActionListener(this::btnCancelarBuscarAutorActionPerformed);

        jLabelNombreBuscarAutor.setText("Nombre:");

        jLabelFechaNacimientoBuscarAutor.setText("Fecha de Nacimiento:");

        jLabelCedulaBuscarAutor.setText("Cedula:");

        jLabelGeneroLiterarioBuscarAutor.setText("Genero Literario:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBuscarAutor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBuscarAutor.setText("BUSCAR AUTOR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabelBuscarAutor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarAutor)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelTelefonoBuscarAutor.setText("Telefono:");

        jLabelNacionalidadBuscarAutor.setText("Nacionalidad:");

        jLabelBibliografiaBuscarAutor.setText("Bibliografia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtBuscarAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelNombreBuscarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtBuscarAutorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelCedulaBuscarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtBuscarAutorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelApellidoBuscarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtBuscarAutorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelNacionalidadBuscarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtBuscarAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelTelefonoBuscarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtBuscarAutorGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelGeneroLiterarioBuscarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFechaNacimientoBuscarAutor)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCancelarBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelBibliografiaBuscarAutor)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBuscarAutorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBuscarAutorBibliografia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCedulaBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNombreBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelApellidoBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNacionalidadBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefonoBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGeneroLiterarioBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaNacimientoBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBibliografiaBuscarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarAutorBibliografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAutorActionPerformed

    private void btnCancelarBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBuscarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarBuscarAutorActionPerformed

    private void btbGuardarUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGuardarUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbGuardarUsuario2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbGuardarUsuario2;
    private javax.swing.JButton btnBuscarAutor;
    private javax.swing.JButton btnCancelarBuscarAutor;
    private javax.swing.JLabel jLabelApellidoBuscarAutor;
    private javax.swing.JLabel jLabelBibliografiaBuscarAutor;
    private javax.swing.JLabel jLabelBuscarAutor;
    private javax.swing.JLabel jLabelCedulaBuscarAutor;
    private javax.swing.JLabel jLabelFechaNacimientoBuscarAutor;
    private javax.swing.JLabel jLabelGeneroLiterarioBuscarAutor;
    private javax.swing.JLabel jLabelNacionalidadBuscarAutor;
    private javax.swing.JLabel jLabelNombreBuscarAutor;
    private javax.swing.JLabel jLabelTelefonoBuscarAutor;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtBuscarAutorApellido;
    private javax.swing.JTextField txtBuscarAutorBibliografia;
    private javax.swing.JTextField txtBuscarAutorCedula;
    private javax.swing.JTextField txtBuscarAutorFecha;
    private javax.swing.JTextField txtBuscarAutorGenero;
    private javax.swing.JTextField txtBuscarAutorNacionalidad;
    private javax.swing.JTextField txtBuscarAutorNombre;
    private javax.swing.JTextField txtBuscarAutorTelefono;
    // End of variables declaration//GEN-END:variables
}
