/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabibliotecaview.menuview.AutorView;

/**
 *
 * @author katherine
 */
public class EliminarAutorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarAutorView
     */
    public EliminarAutorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEliminarAutorNombre = new javax.swing.JTextField();
        txtEliminarAutorTelefono = new javax.swing.JTextField();
        btnEliminarAutor = new javax.swing.JButton();
        jLabelApellidoEliminarAutor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelEliminarAutor = new javax.swing.JLabel();
        txtEliminarAutorBibliografia = new javax.swing.JTextField();
        jLabelGeneroLiterarioEliminarAutor = new javax.swing.JLabel();
        txtEliminarAutorApellido = new javax.swing.JTextField();
        txtEliminarAutorGenero = new javax.swing.JTextField();
        jLabelCedulaEliminarAutor = new javax.swing.JLabel();
        jLabelFechaNacimientoEliminarAutor = new javax.swing.JLabel();
        btnBuscarEliminarAutor = new javax.swing.JButton();
        jLabelBibiografiaEliminarAutor = new javax.swing.JLabel();
        txtEliminarAutorCedula = new javax.swing.JTextField();
        jLabelNombreEliminarAutor = new javax.swing.JLabel();
        jLabelNacionalidadEliminarAutor = new javax.swing.JLabel();
        txtEliminarAutorFecha = new javax.swing.JTextField();
        txtEliminarAutorNacionalidad = new javax.swing.JTextField();
        btbCancelarEliminarAutor = new javax.swing.JButton();
        jLabelTelefonoEliminarAutor = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Autor");

        btnEliminarAutor.setBackground(new java.awt.Color(0, 102, 153));
        btnEliminarAutor.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAutor.setText("Eliminar");
        btnEliminarAutor.addActionListener(this::btnEliminarAutorActionPerformed);

        jLabelApellidoEliminarAutor.setText("Apellido:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEliminarAutor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEliminarAutor.setText("ELIMINAR AUTOR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabelEliminarAutor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEliminarAutor)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelGeneroLiterarioEliminarAutor.setText("Genero Literario:");

        jLabelCedulaEliminarAutor.setText("Cedula:");

        jLabelFechaNacimientoEliminarAutor.setText("Fecha de Nacimiento:");

        btnBuscarEliminarAutor.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarEliminarAutor.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEliminarAutor.setText("Buscar");
        btnBuscarEliminarAutor.addActionListener(this::btnBuscarEliminarAutorActionPerformed);

        jLabelBibiografiaEliminarAutor.setText("Bibliografia:");

        jLabelNombreEliminarAutor.setText("Nombre:");

        jLabelNacionalidadEliminarAutor.setText("Nacionalidad:");

        btbCancelarEliminarAutor.setText("Cancelar");
        btbCancelarEliminarAutor.addActionListener(this::btbCancelarEliminarAutorActionPerformed);

        jLabelTelefonoEliminarAutor.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelNombreEliminarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarAutorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelCedulaEliminarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarAutorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelApellidoEliminarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarAutorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelNacionalidadEliminarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelTelefonoEliminarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarAutorGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelGeneroLiterarioEliminarAutor))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFechaNacimientoEliminarAutor)
                                .addComponent(jLabelBibiografiaEliminarAutor)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEliminarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btbCancelarEliminarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEliminarAutorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEliminarAutorBibliografia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarEliminarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCedulaEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEliminarAutorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEliminarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNombreEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelApellidoEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarAutorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNacionalidadEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarAutorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefonoEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGeneroLiterarioEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarAutorGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaNacimientoEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarAutorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBibiografiaEliminarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarAutorBibliografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbCancelarEliminarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarAutorActionPerformed

    private void btnBuscarEliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEliminarAutorActionPerformed

    private void btbCancelarEliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarEliminarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbCancelarEliminarAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancelarEliminarAutor;
    private javax.swing.JButton btnBuscarEliminarAutor;
    private javax.swing.JButton btnEliminarAutor;
    private javax.swing.JLabel jLabelApellidoEliminarAutor;
    private javax.swing.JLabel jLabelBibiografiaEliminarAutor;
    private javax.swing.JLabel jLabelCedulaEliminarAutor;
    private javax.swing.JLabel jLabelEliminarAutor;
    private javax.swing.JLabel jLabelFechaNacimientoEliminarAutor;
    private javax.swing.JLabel jLabelGeneroLiterarioEliminarAutor;
    private javax.swing.JLabel jLabelNacionalidadEliminarAutor;
    private javax.swing.JLabel jLabelNombreEliminarAutor;
    private javax.swing.JLabel jLabelTelefonoEliminarAutor;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtEliminarAutorApellido;
    private javax.swing.JTextField txtEliminarAutorBibliografia;
    private javax.swing.JTextField txtEliminarAutorCedula;
    private javax.swing.JTextField txtEliminarAutorFecha;
    private javax.swing.JTextField txtEliminarAutorGenero;
    private javax.swing.JTextField txtEliminarAutorNacionalidad;
    private javax.swing.JTextField txtEliminarAutorNombre;
    private javax.swing.JTextField txtEliminarAutorTelefono;
    // End of variables declaration//GEN-END:variables
}
