/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabibliotecaview.menuview.BibliotecarioView;

/**
 *
 * @author katherine
 */
public class EliminarBibliotecarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarBibliotecarioView
     */
    public EliminarBibliotecarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelEliminarBibliotecario = new javax.swing.JLabel();
        jLabelCedulaEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminarCedulaBibliotecario = new javax.swing.JTextField();
        jLabelNombreEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminaNombreBibliotecario = new javax.swing.JTextField();
        jLabelApellidoEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminarApellidoBibliotecario = new javax.swing.JTextField();
        jLabelCargoEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminarCargoBibliotecario = new javax.swing.JTextField();
        jLabelTelefonoEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminarTelefonoBibliotecario = new javax.swing.JTextField();
        jLabelCodigoEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminarCodigoBibliotecario = new javax.swing.JTextField();
        jLabelFechaNacimientoEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminarFechaBibliotecario = new javax.swing.JTextField();
        btbCancelarEliminarBibliotecario = new javax.swing.JButton();
        btnGuardarEliminarBibliotecario = new javax.swing.JButton();
        jLabelTurnoEliminarBibliotecario = new javax.swing.JLabel();
        txtEliminarTurnoBibliotecario = new javax.swing.JTextField();
        btnBuscarEliminarBibliotecario = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Bibliotecario");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEliminarBibliotecario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEliminarBibliotecario.setText("REGISTRO DE BIBLIOTECARIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEliminarBibliotecario)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEliminarBibliotecario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelCedulaEliminarBibliotecario.setText("Cedula:");

        jLabelNombreEliminarBibliotecario.setText("Nombre:");

        jLabelApellidoEliminarBibliotecario.setText("Apellido:");

        jLabelCargoEliminarBibliotecario.setText("Cargo:");

        jLabelTelefonoEliminarBibliotecario.setText("Telefono:");

        jLabelCodigoEliminarBibliotecario.setText("Codigo:");

        jLabelFechaNacimientoEliminarBibliotecario.setText("Fecha de Nacimiento:");

        btbCancelarEliminarBibliotecario.setText("Cancelar");
        btbCancelarEliminarBibliotecario.addActionListener(this::btbCancelarEliminarBibliotecarioActionPerformed);

        btnGuardarEliminarBibliotecario.setBackground(new java.awt.Color(0, 102, 153));
        btnGuardarEliminarBibliotecario.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEliminarBibliotecario.setText("Guardar");
        btnGuardarEliminarBibliotecario.addActionListener(this::btnGuardarEliminarBibliotecarioActionPerformed);

        jLabelTurnoEliminarBibliotecario.setText("Turno:");

        btnBuscarEliminarBibliotecario.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarEliminarBibliotecario.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEliminarBibliotecario.setText("Buscar");
        btnBuscarEliminarBibliotecario.addActionListener(this::btnBuscarEliminarBibliotecarioActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminaNombreBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelNombreEliminarBibliotecario))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarCedulaBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelCedulaEliminarBibliotecario))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarApellidoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelApellidoEliminarBibliotecario))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarCargoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelCargoEliminarBibliotecario))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarTelefonoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelTelefonoEliminarBibliotecario))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtEliminarCodigoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelCodigoEliminarBibliotecario))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFechaNacimientoEliminarBibliotecario)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelTurnoEliminarBibliotecario)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(txtEliminarTurnoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEliminarFechaBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(btnGuardarEliminarBibliotecario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btbCancelarEliminarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarEliminarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCedulaEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEliminarCedulaBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEliminarBibliotecario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNombreEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminaNombreBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelApellidoEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarApellidoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCargoEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarCargoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefonoEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarTelefonoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCodigoEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarCodigoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaNacimientoEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarFechaBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTurnoEliminarBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEliminarTurnoBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEliminarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbCancelarEliminarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbCancelarEliminarBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelarEliminarBibliotecarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbCancelarEliminarBibliotecarioActionPerformed

    private void btnGuardarEliminarBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEliminarBibliotecarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEliminarBibliotecarioActionPerformed

    private void btnBuscarEliminarBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarBibliotecarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEliminarBibliotecarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancelarEliminarBibliotecario;
    private javax.swing.JButton btnBuscarEliminarBibliotecario;
    private javax.swing.JButton btnGuardarEliminarBibliotecario;
    private javax.swing.JLabel jLabelApellidoEliminarBibliotecario;
    private javax.swing.JLabel jLabelCargoEliminarBibliotecario;
    private javax.swing.JLabel jLabelCedulaEliminarBibliotecario;
    private javax.swing.JLabel jLabelCodigoEliminarBibliotecario;
    private javax.swing.JLabel jLabelEliminarBibliotecario;
    private javax.swing.JLabel jLabelFechaNacimientoEliminarBibliotecario;
    private javax.swing.JLabel jLabelNombreEliminarBibliotecario;
    private javax.swing.JLabel jLabelTelefonoEliminarBibliotecario;
    private javax.swing.JLabel jLabelTurnoEliminarBibliotecario;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtEliminaNombreBibliotecario;
    private javax.swing.JTextField txtEliminarApellidoBibliotecario;
    private javax.swing.JTextField txtEliminarCargoBibliotecario;
    private javax.swing.JTextField txtEliminarCedulaBibliotecario;
    private javax.swing.JTextField txtEliminarCodigoBibliotecario;
    private javax.swing.JTextField txtEliminarFechaBibliotecario;
    private javax.swing.JTextField txtEliminarTelefonoBibliotecario;
    private javax.swing.JTextField txtEliminarTurnoBibliotecario;
    // End of variables declaration//GEN-END:variables
}
